SELECT * FROM diwali_sales ;

/*Purchases between different Age groups*/
SELECT SUM(Orders) AS Order_per_age_group ,
`Age Group` FROM diwali_sales 
group by `Age Group`
ORDER BY Order_per_age_group DESC;

/*Purchases between different Genders*/
SELECT SUM(Orders) AS Order_per_gender,
Product_Category,
Gender FROM diwali_sales 
GROUP by Gender, Product_Category
order by Order_per_gender DESC;

/*Purchase patterns based on marital status*/
SELECT Marital_Status,
SUM(Orders) AS total_purchases
FROM diwali_sales
group by Marital_Status
ORDER BY total_purchases;

/*Total reveune generated by different age groups*/
SELECT sum(Amount) AS Amount_per_age_group ,
`Age Group` FROM diwali_sales 
group by `Age Group`
ORDER BY Amount_per_age_group DESC;

/*Total_revenue generated by different gender*/
SELECT SUM(Amount) AS Amount_per_gender,
Product_Category,
Gender FROM diwali_sales 
GROUP by Gender,
Product_Category
order by Amount_per_gender DESC;

/*Total revenue generated by marital status*/
SELECT Marital_Status,
SUM(Amount) AS total_purchases
FROM diwali_sales
group by Marital_Status
ORDER BY total_purchases;

/*Product Categories with highest orders*/
SELECT distinct SUM(Orders) AS Total_No_of_Orders , 
Product_Category 
FROM diwali_sales
group by Product_Category 
order by count(Orders) DESC;

/* Product Categories with highest Sales*/
SELECT distinct SUM(Amount) AS Total_Sales , 
Product_Category 
FROM diwali_sales
group by Product_Category 
order by SUM(Amount) DESC;

/* Top 10 Most Spending customers During Diwali*/
SELECT User_ID, Cust_name, SUM(Amount) AS SALES_AMOUNT 
FROM diwali_sales 
GROUP BY User_ID, Cust_name
ORDER BY Sales_AMOUNT DESC 
LIMIT 10;

/* States With highest TOtal Revenue */
SELECT State, SUM(Amount) AS Sales_per_state 
FROM diwali_sales 
GROUP BY State
ORDER BY Sales_per_state DESC;

/*States with highest Total Orders*/
SELECT State, Sum(Orders) AS Total_order_per_state
FROM diwali_sales
Group BY State
ORDER BY Total_order_per_state DESC;

/*Zones with highest revenue*/
SELECT Zone, Sum(Amount) AS Revenue_asper_zone
FROM diwali_sales
Group BY Zone
ORDER BY Revenue_asper_zone DESC;

/*Zones with highest ORDERS*/
SELECT Zone, Sum(Orders) AS Total_order_per_zone
FROM diwali_sales
Group BY Zone
ORDER BY Total_order_per_zone DESC;

/* Region specific preference for Products for Central Region*/
Select Product_Category, 
sum(Orders) AS Total_Orders 
FROM diwali_sales 
WHERE Zone = 'Central'
GROUP BY Product_Category 
ORDER BY Total_Orders DESC;

/* Region specific products for Western region*/
Select Product_Category, 
sum(Orders) AS Total_Orders 
FROM diwali_sales 
WHERE Zone = 'Western'
GROUP BY Product_Category 
ORDER BY Total_Orders DESC;

/* Region specific products for Southern region*/
Select Product_Category, 
sum(Orders) AS Total_Orders 
FROM diwali_sales 
WHERE Zone = 'Southern'
GROUP BY Product_Category 
ORDER BY Total_Orders DESC;

/* Region specific products for Eastern region*/
Select Product_Category, 
sum(Orders) AS Total_Orders 
FROM diwali_sales 
WHERE Zone = 'Eastern'
GROUP BY Product_Category 
ORDER BY Total_Orders DESC;

/* Region specific products for Northern region*/
Select Product_Category, 
sum(Orders) AS Total_Orders 
FROM diwali_sales 
WHERE Zone = 'Northern'
GROUP BY Product_Category 
ORDER BY Total_Orders DESC;

/* How many users placed multiple orders*/
Select User_ID, Cust_name, sum(Orders) AS Total_Orders , sum(Amount) AS Total_Revenue
FROM diwali_sales
GROUP BY User_ID,Cust_name
Order BY Total_Orders DESC;

/*Purchasing patterns of frequently ordering customners*/
SELECT User_ID, Cust_name, SUM(Orders) AS total_orders, SUM(Amount) AS total_revenue
FROM diwali_sales
GROUP BY User_ID, Cust_name
HAVING total_orders > 29
ORDER BY total_revenue DESC;

/*Purchasing patterns of less frequent;y ordering customers*/
SELECT User_ID, Cust_name, SUM(Orders) AS total_orders, SUM(Amount) AS total_revenue
FROM diwali_sales
GROUP BY User_ID, Cust_name
HAVING total_orders < 29
ORDER BY total_revenue DESC;

/*Running totals of Revenue*/
SELECT
    User_ID,
    Product_ID,
    Amount,
    SUM(Amount) OVER (ORDER BY Product_ID) AS running_total
FROM diwali_sales
ORDER BY User_ID;

/* Ranking top Customers*/
SELECT 
    User_ID,
    Cust_name,
    SUM(Amount) AS total_spent,
    RANK() OVER (ORDER BY SUM(Amount) DESC) AS customer_rank
FROM diwali_sales
GROUP BY User_ID, Cust_name;

/*Ranking by top products generating most revenue*/
SELECT Product_ID,
Product_Category ,
sum(Amount) AS Amt_spent,
RANK() OVER (ORDER BY sum(Amount) DESC) AS Product_rank
FROM diwali_sales
GROUP BY Product_ID, Product_Category;






--Exploring the Dimensions
SELECT DISTINCT State, Zone FROM diwali_sales ORDER BY ZOne;
SELECT DISTINCT OCCUPATION , Product_Category FROM diwali_sales;

--Measures Exploration
SELECT SUM(Amount) AS Total_sales FROM diwali_sales; 
select sum(Orders) AS Total_quantity FROM diwali_sales;
SELECT avg(Age) AS Avg_age FROM diwali_sales;
SELECT * FROM diwali_sales Where State = 'Maharashtra';

SELECT distinct Count(Orders) AS Total_No_of_Orders , 
Product_Category 
FROM diwali_sales
group by Product_Category 
order by count(Orders) DESC;
 
SELECT distinct Count(Amount) AS Total_Revenue , 
Product_Category 
FROM diwali_sales
group by Product_Category 
order by count(Amount) DESC;

SELECT DISTINCT COUNT(Product_ID) AS Totsl_no_of_products FROM diwali_sales;
SELECT DISTINCT COUNT(User_ID) AS Total_no_of_Customers FROM diwali_sales;

--Generating a report that shows all key metrics
SELECT 'Total_sales' AS measure_name, SUM(Amount) AS measure_value FROM diwali_sales 
UNION ALL
select 'Total_Quantity' AS measure_name, sum(Orders) AS meaure_value FROM diwali_sales
UNION ALL
SELECT 'AVERAGE_Age' AS measure_name, avg(Age) AS measure_value FROM diwali_sales
UNION ALL
SELECT 'Total_no_of_products' AS measure_name, COUNT(DISTINCT Product_ID) AS measure_value FROM diwali_sales
UNION ALL
SELECT 'Total NO of customers' AS measure_name, COUNT(DISTINCT User_ID) AS measure_value FROM diwali_sales;


--Magnitude Analysis
SELECT count(Orders) AS Order_per_age_group ,
`Age Group` FROM diwali_sales 
group by `Age Group`
ORDER BY Order_per_age_group DESC;

SELECT COUNT(Orders) AS Order_per_gender,
Gender FROM diwali_sales 
GROUP by Gender ;

SELECT avg(Orders) AS AVG_ORDER_PER_State, State
FROM diwali_sales 
GROUP BY State 
order by AVG_ORDER_PER_State DESC;

SELECT User_ID, Cust_name, SUM(Amount) AS SALES_AMOUNT 
FROM diwali_sales 
GROUP BY User_ID, Cust_name
ORDER BY Sales_AMOUNT DESC 
LIMIT 10;


